# Generated by Django 5.2.2 on 2025-06-24 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sancionempleado',
            name='explorador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones_explorador', to='empleados.empleado'),
        ),
    ]
