# Generated by Django 5.2.2 on 2026-02-08 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_asignacionsalaperiodo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competenciaempleado',
            options={'ordering': ['empleado', 'sala'], 'verbose_name': 'Competencia de Empleado', 'verbose_name_plural': 'Competencias de Empleados'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='empleadorole',
            options={'ordering': ['empleado', 'role'], 'verbose_name': 'Rol de Empleado', 'verbose_name_plural': 'Roles de Empleados'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompetenciaempleado',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Competencia de Empleado', 'verbose_name_plural': 'historical Competencias de Empleados'},
        ),
        migrations.AlterModelOptions(
            name='historicalempleado',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Empleado', 'verbose_name_plural': 'historical Empleados'},
        ),
        migrations.AlterModelOptions(
            name='historicalempleadorole',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Rol de Empleado', 'verbose_name_plural': 'historical Roles de Empleados'},
        ),
        migrations.AlterModelOptions(
            name='historicaljornada',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Jornada', 'verbose_name_plural': 'historical Jornadas'},
        ),
        migrations.AlterModelOptions(
            name='historicalrestriccionempleado',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Restricción de Empleado', 'verbose_name_plural': 'historical Restricciones de Empleados'},
        ),
        migrations.AlterModelOptions(
            name='historicalrole',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Rol', 'verbose_name_plural': 'historical Roles'},
        ),
        migrations.AlterModelOptions(
            name='historicalsala',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sala', 'verbose_name_plural': 'historical Salas'},
        ),
        migrations.AlterModelOptions(
            name='historicalsancionempleado',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Sanción de Empleado', 'verbose_name_plural': 'historical Sanciones de Empleados'},
        ),
        migrations.AlterModelOptions(
            name='jornada',
            options={'ordering': ['nombre'], 'verbose_name': 'Jornada', 'verbose_name_plural': 'Jornadas'},
        ),
        migrations.AlterModelOptions(
            name='restriccionempleado',
            options={'ordering': ['-fecha_inicio', 'empleado'], 'verbose_name': 'Restricción de Empleado', 'verbose_name_plural': 'Restricciones de Empleados'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['nombre'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'ordering': ['nombre'], 'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterModelOptions(
            name='sancionempleado',
            options={'ordering': ['-fecha_inicio', 'explorador'], 'verbose_name': 'Sanción de Empleado', 'verbose_name_plural': 'Sanciones de Empleados'},
        ),
        migrations.AlterUniqueTogether(
            name='competenciaempleado',
            unique_together={('empleado', 'sala')},
        ),
        migrations.AlterUniqueTogether(
            name='empleadorole',
            unique_together={('empleado', 'role')},
        ),
        migrations.AddIndex(
            model_name='competenciaempleado',
            index=models.Index(fields=['empleado', 'sala'], name='comp_emp_sala_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['activo'], name='empleado_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['supervisor', 'activo'], name='empleado_super_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='empleadorole',
            index=models.Index(fields=['empleado', 'role'], name='empleado_role_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='restriccionempleado',
            index=models.Index(fields=['empleado', 'fecha_inicio'], name='rest_emp_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='restriccionempleado',
            index=models.Index(fields=['tipo_restriccion'], name='rest_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='sala',
            index=models.Index(fields=['activo'], name='sala_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='sancionempleado',
            index=models.Index(fields=['explorador', 'fecha_inicio'], name='sanc_exp_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='sancionempleado',
            index=models.Index(fields=['supervisor'], name='sanc_supervisor_idx'),
        ),
    ]
