# Generated by Django 5.2.2 on 2026-06-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_competenciaempleado_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalasignacionsalaperiodo',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='historicalasignacionsalaperiodo',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='historicalasignacionsalaperiodo',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalasignacionsalaperiodo',
            name='sala',
        ),
        migrations.DeleteModel(
            name='AsignacionSalaPeriodo',
        ),
        migrations.DeleteModel(
            name='HistoricalAsignacionSalaPeriodo',
        ),
    ]
