# Generated by Django 5.2.16 on 2026-08-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_remove_historicalasignacionsalaperiodo_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljornada',
            name='nombre',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='nombre',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=5, unique=True),
        ),
    ]
