# Generated by Django 5.2.16 on 2026-08-02 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_historicaljornada_nombre_alter_jornada_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadorole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.role'),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='nombre',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
