# Generated by Django 5.2.16 on 2026-08-02 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_role_nombre_unico_y_empleadorole_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsancionempleado',
            name='levantada_en',
            field=models.DateField(blank=True, help_text='Fecha en que se levantó la sanción. Vacío = sigue su curso normal.', null=True),
        ),
        migrations.AddField(
            model_name='historicalsancionempleado',
            name='levantada_motivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalsancionempleado',
            name='levantada_por',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Supervisor que la levantó (vacío si la levantó el sistema por pago de deuda).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='sancionempleado',
            name='levantada_en',
            field=models.DateField(blank=True, help_text='Fecha en que se levantó la sanción. Vacío = sigue su curso normal.', null=True),
        ),
        migrations.AddField(
            model_name='sancionempleado',
            name='levantada_motivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sancionempleado',
            name='levantada_por',
            field=models.ForeignKey(blank=True, help_text='Supervisor que la levantó (vacío si la levantó el sistema por pago de deuda).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanciones_levantadas', to='empleados.empleado'),
        ),
    ]
