# Generated by Django 5.2.17 on 2026-08-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_historicalsancionempleado_levantada_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsancionempleado',
            name='periodo_anio',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsancionempleado',
            name='periodo_mes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sancionempleado',
            name='periodo_anio',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sancionempleado',
            name='periodo_mes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='sancionempleado',
            index=models.Index(fields=['explorador', 'periodo_anio', 'periodo_mes'], name='sanc_exp_periodo_idx'),
        ),
    ]
