# Generated by Django 5.2.17 on 2026-08-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_historicalsancionempleado_periodo_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsancionempleado',
            name='nivel_reincidencia',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = primera sanción; 2, 3… reincidencias sucesivas. Duración = nivel × 15 días.'),
        ),
        migrations.AddField(
            model_name='sancionempleado',
            name='nivel_reincidencia',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 = primera sanción; 2, 3… reincidencias sucesivas. Duración = nivel × 15 días.'),
        ),
    ]
