# Generated by Django 5.1.7 on 2025-11-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignarjornadaexplorador',
            options={'ordering': ['explorador', '-fecha_inicio']},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha', 'explorador']},
        ),
        migrations.AddIndex(
            model_name='asignarjornadaexplorador',
            index=models.Index(fields=['explorador', 'fecha_inicio'], name='jornada_explorador_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['explorador', 'fecha'], name='turno_explorador_fecha_idx'),
        ),
    ]
