# Generated by Django 5.1.7 on 2025-09-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignarjornadaexplorador',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='historicalasignarjornadaexplorador',
            name='fecha_fin',
        ),
    ]
