# Generated by Django 5.1.7 on 2025-11-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_asignarjornadaexplorador_options_and_more'),
        ('turnos', '0002_remove_fecha_fin_from_asignar_jornada'),
    ]

    operations = [
    ]
