# Generated by Django 5.1.7 on 2025-11-11 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_asignacionsalaperiodo_and_more'),
        ('turnos', '0003_merge_20251111_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_cambio', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_archivado', models.DateTimeField(auto_now_add=True)),
                ('turno_original_id', models.IntegerField(blank=True, help_text='ID del turno original antes de archivar', null=True)),
                ('explorador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.jornada')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.sala')),
            ],
            options={
                'verbose_name': 'Turno Archivado',
                'verbose_name_plural': 'Turnos Archivados',
                'ordering': ['fecha', 'explorador'],
                'indexes': [models.Index(fields=['explorador', 'fecha'], name='turno_arch_exp_fecha_idx'), models.Index(fields=['fecha'], name='turno_arch_fecha_idx')],
            },
        ),
    ]
