# Generated by Django 5.1.7 on 2025-11-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_turnoarchivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaespecial',
            options={'ordering': ['fecha']},
        ),
        migrations.AddField(
            model_name='diaespecial',
            name='año_planificacion',
            field=models.IntegerField(blank=True, help_text='Año al que pertenecen las temporadas', null=True),
        ),
        migrations.AddField(
            model_name='diaespecial',
            name='es_temporada',
            field=models.BooleanField(default=False, help_text='Indica si es un día de temporada'),
        ),
        migrations.AddField(
            model_name='diaespecial',
            name='mes',
            field=models.IntegerField(blank=True, help_text='Mes de la fecha (1-12), calculado automáticamente', null=True),
        ),
        migrations.AddField(
            model_name='historicaldiaespecial',
            name='año_planificacion',
            field=models.IntegerField(blank=True, help_text='Año al que pertenecen las temporadas', null=True),
        ),
        migrations.AddField(
            model_name='historicaldiaespecial',
            name='es_temporada',
            field=models.BooleanField(default=False, help_text='Indica si es un día de temporada'),
        ),
        migrations.AddField(
            model_name='historicaldiaespecial',
            name='mes',
            field=models.IntegerField(blank=True, help_text='Mes de la fecha (1-12), calculado automáticamente', null=True),
        ),
        migrations.AddIndex(
            model_name='diaespecial',
            index=models.Index(fields=['año_planificacion', 'mes', 'es_temporada'], name='dia_esp_anio_mes_temp_idx'),
        ),
        migrations.AddIndex(
            model_name='diaespecial',
            index=models.Index(fields=['fecha', 'tipo', 'activo'], name='dia_esp_fecha_tipo_activo_idx'),
        ),
    ]
