# Generated by Django 5.2.2 on 2026-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_competenciaempleado_options_and_more'),
        ('turnos', '0005_add_temporada_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignarsalaexplorador',
            options={'ordering': ['-fecha_inicio', 'explorador'], 'verbose_name': 'Asignación de Sala a Explorador', 'verbose_name_plural': 'Asignaciones de Sala a Exploradores'},
        ),
        migrations.AlterModelOptions(
            name='historicalasignarsalaexplorador',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Asignación de Sala a Explorador', 'verbose_name_plural': 'historical Asignaciones de Sala a Exploradores'},
        ),
        migrations.AddIndex(
            model_name='asignarsalaexplorador',
            index=models.Index(fields=['explorador', 'fecha_inicio'], name='asig_sala_exp_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='asignarsalaexplorador',
            index=models.Index(fields=['sala'], name='asig_sala_sala_idx'),
        ),
    ]
