# Generated by Django 5.2.2 on 2026-06-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_alter_asignarsalaexplorador_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalasignarsalaexplorador',
            name='explorador',
        ),
        migrations.RemoveField(
            model_name='historicalasignarsalaexplorador',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalasignarsalaexplorador',
            name='sala',
        ),
        migrations.DeleteModel(
            name='AsignarSalaExplorador',
        ),
        migrations.DeleteModel(
            name='HistoricalAsignarSalaExplorador',
        ),
    ]
