# Generated by Django 5.2.2 on 2026-06-19 21:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_remove_historicalasignacionsalaperiodo_creado_por_and_more'),
        ('turnos', '0007_remove_historicalasignarsalaexplorador_explorador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDescansoSemanaManual',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Día (lunes a viernes) en que descansa la jornada indicada')),
                ('motivo', models.CharField(choices=[('temporada', 'Temporada'), ('festivo', 'Festivo'), ('otro', 'Otro')], default='temporada', help_text='Por qué esta semana el descanso es manual (temporada/festivo)', max_length=20)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('jornada', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.jornada')),
            ],
            options={
                'verbose_name': 'historical Descanso de semana (manual)',
                'verbose_name_plural': 'historical Descansos de semana (manuales)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DescansoSemanaManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Día (lunes a viernes) en que descansa la jornada indicada')),
                ('motivo', models.CharField(choices=[('temporada', 'Temporada'), ('festivo', 'Festivo'), ('otro', 'Otro')], default='temporada', help_text='Por qué esta semana el descanso es manual (temporada/festivo)', max_length=20)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descansos_semana_manual', to='empleados.jornada')),
            ],
            options={
                'verbose_name': 'Descanso de semana (manual)',
                'verbose_name_plural': 'Descansos de semana (manuales)',
                'ordering': ['-fecha', 'jornada'],
                'indexes': [models.Index(fields=['fecha', 'activo'], name='descsem_fecha_activo_idx')],
                'constraints': [models.UniqueConstraint(fields=('fecha', 'jornada'), name='uniq_descanso_semana_fecha_jornada')],
            },
        ),
    ]
