# Generated by Django 5.2.2 on 2026-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_historicalasignacionespecialmanual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalturno',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalturno',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turno',
            name='motivo_anulacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
