# Generated by Django 5.2.16 on 2026-07-26 06:33

from django.db import migrations, models


def preparar_datos(apps, schema_editor):
    """
    Deja los datos existentes en condiciones de aceptar la restricción de unicidad.

    1. Los turnos ANULADOS pasan a `activo_key = NULL` (el default los dejó en 1). Los NULL no
       colisionan entre sí en un índice único, que es justo lo que permite conservar varios
       anulados para el mismo (explorador, fecha, jornada).
    2. Los duplicados ACTIVOS históricos —lo que la restricción viene a impedir— se resuelven
       conservando el más antiguo (id menor) y ANULANDO los demás. No se borra nada: el
       soft-delete es el mecanismo de auditoría del proyecto, y estos casos hay que poder
       revisarlos después. Si esta migración anula filas, conviene mirar el log: cada una
       significa que alguna ruta creó un turno sin borrar el anterior.
    """
    Turno = apps.get_model('turnos', 'Turno')

    Turno.objects.filter(anulado=True).update(activo_key=None)

    vistos = set()
    duplicados = []
    activos = (
        Turno.objects
        .filter(anulado=False)
        .order_by('explorador_id', 'fecha', 'jornada_id', 'id')
        .values_list('id', 'explorador_id', 'fecha', 'jornada_id')
    )
    for turno_id, explorador_id, fecha, jornada_id in activos.iterator():
        clave = (explorador_id, fecha, jornada_id)
        if clave in vistos:
            duplicados.append(turno_id)
        else:
            vistos.add(clave)

    if duplicados:
        Turno.objects.filter(id__in=duplicados).update(
            anulado=True,
            activo_key=None,
            motivo_anulacion='Duplicado activo detectado al aplicar turno_unico_activo_por_jornada',
        )
        print(f'  turnos: {len(duplicados)} turno(s) duplicado(s) activo(s) anulado(s) '
              f'para poder aplicar la restricción de unicidad.')


def revertir_datos(apps, schema_editor):
    """La restricción se puede quitar; los datos anulados no se re-activan automáticamente
    (no sabemos cuáles eran duplicados reales y cuáles anulaciones legítimas previas)."""
    Turno = apps.get_model('turnos', 'Turno')
    Turno.objects.filter(activo_key__isnull=True, anulado=False).update(activo_key=1)


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_remove_historicalasignacionsalaperiodo_creado_por_and_more'),
        ('turnos', '0010_historicalturno_anulado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalturno',
            name='activo_key',
            field=models.PositiveSmallIntegerField(blank=True, default=1, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='activo_key',
            field=models.PositiveSmallIntegerField(blank=True, default=1, editable=False, null=True),
        ),
        migrations.RunPython(preparar_datos, revertir_datos),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('explorador', 'fecha', 'jornada', 'activo_key'), name='turno_unico_activo_por_jornada'),
        ),
    ]
