# Generated by Django 5.2.16 on 2026-07-29 07:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0011_turno_unico_activo_por_jornada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaAnioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_recordatorio_dia', models.PositiveSmallIntegerField(default=1, help_text='Día del mes en que empieza el aviso en el dashboard.')),
                ('inicio_recordatorio_mes', models.PositiveSmallIntegerField(default=11, help_text='Mes en que empieza el aviso (1-12). Por defecto noviembre.')),
                ('inicio_bloqueo_dia', models.PositiveSmallIntegerField(default=1, help_text='Día del mes en que empieza el bloqueo.')),
                ('inicio_bloqueo_mes', models.PositiveSmallIntegerField(default=12, help_text='Mes en que empieza el bloqueo (1-12). Por defecto diciembre.')),
                ('bloqueo_duro', models.BooleanField(default=True, help_text='Si está apagado, solo se avisa: nunca se redirige al supervisor.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apertura de año (config)',
                'verbose_name_plural': 'Apertura de año (config)',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAperturaAnioConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('inicio_recordatorio_dia', models.PositiveSmallIntegerField(default=1, help_text='Día del mes en que empieza el aviso en el dashboard.')),
                ('inicio_recordatorio_mes', models.PositiveSmallIntegerField(default=11, help_text='Mes en que empieza el aviso (1-12). Por defecto noviembre.')),
                ('inicio_bloqueo_dia', models.PositiveSmallIntegerField(default=1, help_text='Día del mes en que empieza el bloqueo.')),
                ('inicio_bloqueo_mes', models.PositiveSmallIntegerField(default=12, help_text='Mes en que empieza el bloqueo (1-12). Por defecto diciembre.')),
                ('bloqueo_duro', models.BooleanField(default=True, help_text='Si está apagado, solo se avisa: nunca se redirige al supervisor.')),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Apertura de año (config)',
                'verbose_name_plural': 'historical Apertura de año (config)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
