# Generated by Django 5.2.16 on 2026-08-01 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_historicaljornada_nombre_alter_jornada_nombre'),
        ('turnos', '0013_diaespecial_tipo_choices_y_unicidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionespecialmanual',
            name='jornada_trabaja',
            field=models.ForeignKey(help_text='Grupo (AM/PM) que TRABAJA el día completo (dobla). El otro grupo descansa.', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_especiales_manual', to='empleados.jornada'),
        ),
        migrations.AlterField(
            model_name='asignarjornadaexplorador',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.jornada'),
        ),
        migrations.AlterField(
            model_name='descansosemanamanual',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descansos_semana_manual', to='empleados.jornada'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.jornada'),
        ),
        migrations.AlterField(
            model_name='turnoarchivo',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.jornada'),
        ),
    ]
