# Generated by Django 5.2.16 on 2026-08-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_historicalsancionempleado_levantada_en_and_more'),
        ('turnos', '0014_alter_asignacionespecialmanual_jornada_trabaja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalturno',
            name='tipo_cambio',
            field=models.CharField(blank=True, choices=[('CT', 'Cambio de turno'), ('DOBLADA PERM', 'Doblada permanente'), ('PAGO REPROGRAMADO', 'Pago reprogramado'), ('PERMISO', 'Permiso'), ('DOBLADA', 'Doblada'), ('CAMBIO DESCANSO', 'Cambio de descanso'), ('CT PERMANENTE', 'CT permanente'), ('D FDS', 'Día fin de semana')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='tipo_cambio',
            field=models.CharField(blank=True, choices=[('CT', 'Cambio de turno'), ('DOBLADA PERM', 'Doblada permanente'), ('PAGO REPROGRAMADO', 'Pago reprogramado'), ('PERMISO', 'Permiso'), ('DOBLADA', 'Doblada'), ('CAMBIO DESCANSO', 'Cambio de descanso'), ('CT PERMANENTE', 'CT permanente'), ('D FDS', 'Día fin de semana')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='turnoarchivo',
            name='tipo_cambio',
            field=models.CharField(blank=True, choices=[('CT', 'Cambio de turno'), ('DOBLADA PERM', 'Doblada permanente'), ('PAGO REPROGRAMADO', 'Pago reprogramado'), ('PERMISO', 'Permiso'), ('DOBLADA', 'Doblada'), ('CAMBIO DESCANSO', 'Cambio de descanso'), ('CT PERMANENTE', 'CT permanente'), ('D FDS', 'Día fin de semana')], max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_cambio__isnull', True), ('tipo_cambio__in', ('CT', 'DOBLADA PERM', 'PAGO REPROGRAMADO', 'PERMISO', 'DOBLADA', 'CAMBIO DESCANSO', 'CT PERMANENTE', 'D FDS')), _connector='OR'), name='turno_tipo_cambio_valido'),
        ),
    ]
