# Generated by Django 5.2.17 on 2026-09-02 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0011_historicalpermisosesion_permisosesion'),
        ('turnos', '0015_alter_historicalturno_tipo_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.sala'),
        ),
        migrations.AlterField(
            model_name='turnoarchivo',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.sala'),
        ),
    ]
