# Generated by Django 5.1.7 on 2025-08-23 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('permisos', '0001_initial'),
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpdh',
            name='solicitud',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.solicitudcambio'),
        ),
        migrations.AddField(
            model_name='historicalpdh',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='empleado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='pdh',
            name='explorador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_explorador', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='pdh',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_solicitud', to='solicitudes.solicitudcambio'),
        ),
        migrations.AddField(
            model_name='pdh',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_pdh', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_especiales', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_supervisor', to='empleados.empleado'),
        ),
    ]
