# Generated by Django 5.2.2 on 2026-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_competenciaempleado_options_and_more'),
        ('permisos', '0002_initial'),
        ('solicitudes', '0011_alter_cambiopermanentedetalle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpdh',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical PDH', 'verbose_name_plural': 'historical PDHs'},
        ),
        migrations.AlterModelOptions(
            name='pdh',
            options={'ordering': ['-fecha', 'explorador'], 'verbose_name': 'PDH', 'verbose_name_plural': 'PDHs'},
        ),
        migrations.AlterModelOptions(
            name='permisoespecial',
            options={'ordering': ['-fecha_inicio', 'empleado'], 'verbose_name': 'Permiso Especial', 'verbose_name_plural': 'Permisos Especiales'},
        ),
        migrations.AddIndex(
            model_name='pdh',
            index=models.Index(fields=['explorador', 'fecha'], name='pdh_exp_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='pdh',
            index=models.Index(fields=['solicitud'], name='pdh_solicitud_idx'),
        ),
        migrations.AddIndex(
            model_name='pdh',
            index=models.Index(fields=['fecha'], name='pdh_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='permisoespecial',
            index=models.Index(fields=['empleado', 'estado'], name='perm_esp_emp_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='permisoespecial',
            index=models.Index(fields=['estado'], name='perm_esp_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='permisoespecial',
            index=models.Index(fields=['fecha_inicio'], name='perm_esp_fecha_idx'),
        ),
    ]
