# Generated by Django 5.2.2 on 2026-06-12 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_competenciaempleado_options_and_more'),
        ('permisos', '0003_alter_historicalpdh_options_alter_pdh_options_and_more'),
        ('solicitudes', '0015_alter_historicaldobladadetalle_jornada_cubre_en_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpdh',
            name='fecha',
            field=models.DateField(help_text='Fecha en que se paga la hora'),
        ),
        migrations.AlterField(
            model_name='historicalpdh',
            name='horas',
            field=models.DecimalField(decimal_places=2, help_text='Horas pagadas (se descuentan del consolidado)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='historicalpdh',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Supervisor/líder que autoriza el pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='historicalpdh',
            name='tipo_registro',
            field=models.CharField(default='pago_horas', max_length=50),
        ),
        migrations.AlterField(
            model_name='pdh',
            name='fecha',
            field=models.DateField(help_text='Fecha en que se paga la hora'),
        ),
        migrations.AlterField(
            model_name='pdh',
            name='horas',
            field=models.DecimalField(decimal_places=2, help_text='Horas pagadas (se descuentan del consolidado)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pdh',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_solicitud', to='solicitudes.solicitudcambio'),
        ),
        migrations.AlterField(
            model_name='pdh',
            name='supervisor',
            field=models.ForeignKey(help_text='Supervisor/líder que autoriza el pago', on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_pdh', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='pdh',
            name='tipo_registro',
            field=models.CharField(default='pago_horas', max_length=50),
        ),
    ]
