# Generated by Django 5.2.2 on 2026-06-12 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_competenciaempleado_options_and_more'),
        ('permisos', '0004_alter_historicalpdh_fecha_alter_historicalpdh_horas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='cubre',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Compañero que cubre el hueco (opcional).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='dias_semana',
            field=models.CharField(blank=True, default='', help_text='Permanente: días de la semana (0=lun..6=dom) separados por coma.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='es_permanente',
            field=models.BooleanField(default=False, help_text='True si es un permiso permanente (días fijos de la semana).'),
        ),
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='especificacion',
            field=models.CharField(blank=True, default='', help_text='Ej: "Entrada 1:30 pm" / "Salida 5:00 pm".', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='tiempo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas solicitadas por ocurrencia (se acumulan a la deuda del explorador).', max_digits=5),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='cubre',
            field=models.ForeignKey(blank=True, help_text='Compañero que cubre el hueco (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_que_cubre', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='dias_semana',
            field=models.CharField(blank=True, default='', help_text='Permanente: días de la semana (0=lun..6=dom) separados por coma.', max_length=20),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='es_permanente',
            field=models.BooleanField(default=False, help_text='True si es un permiso permanente (días fijos de la semana).'),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='especificacion',
            field=models.CharField(blank=True, default='', help_text='Ej: "Entrada 1:30 pm" / "Salida 5:00 pm".', max_length=120),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='tiempo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas solicitadas por ocurrencia (se acumulan a la deuda del explorador).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='historicalpermisoespecial',
            name='fecha_fin',
            field=models.DateField(help_text='Permiso normal: igual que inicio. Permanente: fin del rango.'),
        ),
        migrations.AlterField(
            model_name='historicalpermisoespecial',
            name='fecha_inicio',
            field=models.DateField(help_text='Permiso normal: el día. Permanente: inicio del rango.'),
        ),
        migrations.AlterField(
            model_name='historicalpermisoespecial',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Supervisor que aprueba/rechaza.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='historicalpermisoespecial',
            name='tipo',
            field=models.CharField(choices=[('MEDICO', 'Médico'), ('PERSONAL', 'Personal'), ('FAMILIAR', 'Familiar'), ('OTRO', 'Otro')], default='PERSONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='permisoespecial',
            name='fecha_fin',
            field=models.DateField(help_text='Permiso normal: igual que inicio. Permanente: fin del rango.'),
        ),
        migrations.AlterField(
            model_name='permisoespecial',
            name='fecha_inicio',
            field=models.DateField(help_text='Permiso normal: el día. Permanente: inicio del rango.'),
        ),
        migrations.AlterField(
            model_name='permisoespecial',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor que aprueba/rechaza.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_supervisor', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='permisoespecial',
            name='tipo',
            field=models.CharField(choices=[('MEDICO', 'Médico'), ('PERSONAL', 'Personal'), ('FAMILIAR', 'Familiar'), ('OTRO', 'Otro')], default='PERSONAL', max_length=20),
        ),
    ]
