# Generated by Django 5.2.2 on 2026-06-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0005_historicalpermisoespecial_cubre_and_more'),
        ('solicitudes', '0020_deudacorporativa_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='Fecha en que se pagó la deuda de este permiso.', null=True),
        ),
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='pagado',
            field=models.BooleanField(default=False, help_text='True si la deuda de este permiso ya fue pagada (PDH).'),
        ),
        migrations.AddField(
            model_name='pdh',
            name='deudas_pagadas',
            field=models.ManyToManyField(blank=True, help_text='Dobladas (0.5 h c/u) que paga este registro.', related_name='pdhs_pago', to='solicitudes.deudacorporativa'),
        ),
        migrations.AddField(
            model_name='pdh',
            name='permisos_pagados',
            field=models.ManyToManyField(blank=True, help_text='Permisos aprobados que paga este registro.', related_name='pdhs_pago', to='permisos.permisoespecial'),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='Fecha en que se pagó la deuda de este permiso.', null=True),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='pagado',
            field=models.BooleanField(default=False, help_text='True si la deuda de este permiso ya fue pagada (PDH).'),
        ),
    ]
