# Generated by Django 5.2.2 on 2026-07-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0006_historicalpermisoespecial_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='fecha_compensacion',
            field=models.DateField(blank=True, help_text='Media jornada temporada: día de descanso de la MISMA semana donde trabaja la media jornada restante.', null=True),
        ),
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='jornada_trabaja',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Media jornada temporada: jornada que trabajará en su día completo (fecha_inicio). La otra media se trabaja en fecha_compensacion. Sin deuda (tiempo=0).', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='snapshot_turnos_previos',
            field=models.JSONField(blank=True, help_text='Turnos previos del empleado en fecha_inicio y fecha_compensacion antes de aplicar el permiso aprobado (mismo formato que DobladaDetalle). Permite revertir.', null=True),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='fecha_compensacion',
            field=models.DateField(blank=True, help_text='Media jornada temporada: día de descanso de la MISMA semana donde trabaja la media jornada restante.', null=True),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='jornada_trabaja',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Media jornada temporada: jornada que trabajará en su día completo (fecha_inicio). La otra media se trabaja en fecha_compensacion. Sin deuda (tiempo=0).', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='snapshot_turnos_previos',
            field=models.JSONField(blank=True, help_text='Turnos previos del empleado en fecha_inicio y fecha_compensacion antes de aplicar el permiso aprobado (mismo formato que DobladaDetalle). Permite revertir.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpermisoespecial',
            name='tipo',
            field=models.CharField(choices=[('MEDICO', 'Médico'), ('PERSONAL', 'Personal'), ('FAMILIAR', 'Familiar'), ('MEDIA_JORNADA_TEMPORADA', 'Media jornada temporada (compensada)'), ('OTRO', 'Otro')], default='PERSONAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='permisoespecial',
            name='tipo',
            field=models.CharField(choices=[('MEDICO', 'Médico'), ('PERSONAL', 'Personal'), ('FAMILIAR', 'Familiar'), ('MEDIA_JORNADA_TEMPORADA', 'Media jornada temporada (compensada)'), ('OTRO', 'Otro')], default='PERSONAL', max_length=30),
        ),
    ]
