# Generated by Django 5.2.16 on 2026-08-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_historicalsancionempleado_levantada_en_and_more'),
        ('permisos', '0007_historicalpermisoespecial_fecha_compensacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='cancelacion_estado',
            field=models.CharField(blank=True, choices=[('', '—'), ('pendiente', 'Cancelación pendiente'), ('aprobada', 'Cancelación aprobada'), ('rechazada', 'Cancelación rechazada'), ('caducada', 'Cancelación caducada')], default='', help_text='Estado de la petición de cancelación. Vacío si nunca se pidió cancelar.', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='cancelacion_motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='cancelacion_respondida_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='cancelacion_respondida_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='cancelacion_solicitada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='cancelacion_solicitada_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='cancelacion_estado',
            field=models.CharField(blank=True, choices=[('', '—'), ('pendiente', 'Cancelación pendiente'), ('aprobada', 'Cancelación aprobada'), ('rechazada', 'Cancelación rechazada'), ('caducada', 'Cancelación caducada')], default='', help_text='Estado de la petición de cancelación. Vacío si nunca se pidió cancelar.', max_length=10),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='cancelacion_motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='cancelacion_respondida_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='cancelacion_respondida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_cancelacion_respondida', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='cancelacion_solicitada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='cancelacion_solicitada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_cancelacion_pedida', to='empleados.empleado'),
        ),
    ]
