# Generated by Django 5.2.16 on 2026-08-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0008_historicalpermisoespecial_cancelacion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermisoespecial',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, help_text='Instante en que el permiso quedó APROBADO. Null si nunca se aprobó.', null=True),
        ),
        migrations.AddField(
            model_name='permisoespecial',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, help_text='Instante en que el permiso quedó APROBADO. Null si nunca se aprobó.', null=True),
        ),
    ]
