# Generated by Django 5.2.17 on 2026-08-25 05:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_historicalsancionempleado_levantada_en_and_more'),
        ('permisos', '0009_historicalpermisoespecial_fecha_aprobacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeudaPermisoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(help_text='1..12')),
                ('minutos_generados', models.PositiveIntegerField(help_text='Tiempo del permiso × ocurrencias en ESE mes.')),
                ('minutos_pagados', models.PositiveIntegerField(default=0, help_text='Lo abonado hasta ahora. Permite el pago parcial.')),
                ('ocurrencias', models.PositiveSmallIntegerField(help_text='Cuántos días del permiso caen en ese mes (trazabilidad del cálculo).')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pagada', 'Pagada'), ('consumida_por_sancion', 'Consumida por sanción'), ('cancelada', 'Cancelada')], default='activa', max_length=25)),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha del pago que la SALDÓ (no la del primer abono parcial).', null=True)),
                ('fecha_consumo', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('explorador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas_permiso_mes', to='empleados.empleado')),
                ('permiso', models.ForeignKey(help_text='Permiso que generó esta obligación mensual.', on_delete=django.db.models.deletion.CASCADE, related_name='deudas_mes', to='permisos.permisoespecial')),
                ('sancion_consumidora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deudas_permiso_consumidas', to='empleados.sancionempleado')),
            ],
            options={
                'verbose_name': 'Deuda mensual de permiso',
                'verbose_name_plural': 'Deudas mensuales de permisos',
                'ordering': ['anio', 'mes', 'permiso'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDeudaPermisoMes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(help_text='1..12')),
                ('minutos_generados', models.PositiveIntegerField(help_text='Tiempo del permiso × ocurrencias en ESE mes.')),
                ('minutos_pagados', models.PositiveIntegerField(default=0, help_text='Lo abonado hasta ahora. Permite el pago parcial.')),
                ('ocurrencias', models.PositiveSmallIntegerField(help_text='Cuántos días del permiso caen en ese mes (trazabilidad del cálculo).')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pagada', 'Pagada'), ('consumida_por_sancion', 'Consumida por sanción'), ('cancelada', 'Cancelada')], default='activa', max_length=25)),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha del pago que la SALDÓ (no la del primer abono parcial).', null=True)),
                ('fecha_consumo', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('explorador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('permiso', models.ForeignKey(blank=True, db_constraint=False, help_text='Permiso que generó esta obligación mensual.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='permisos.permisoespecial')),
                ('sancion_consumidora', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.sancionempleado')),
            ],
            options={
                'verbose_name': 'historical Deuda mensual de permiso',
                'verbose_name_plural': 'historical Deudas mensuales de permisos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PagoDeudaPermisoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos', models.PositiveIntegerField(help_text='Minutos de esa deuda que cubre este pago.')),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='permisos.deudapermisomes')),
                ('pdh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_permiso_mes', to='permisos.pdh')),
            ],
            options={
                'verbose_name': 'Detalle de pago de deuda mensual',
                'verbose_name_plural': 'Detalles de pago de deudas mensuales',
            },
        ),
        migrations.AddField(
            model_name='pdh',
            name='deudas_permiso_mes',
            field=models.ManyToManyField(blank=True, help_text='Meses de permiso que paga este registro.', related_name='pdhs', through='permisos.PagoDeudaPermisoMes', to='permisos.deudapermisomes'),
        ),
        migrations.AddIndex(
            model_name='deudapermisomes',
            index=models.Index(fields=['explorador', 'estado'], name='dpm_exp_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='deudapermisomes',
            index=models.Index(fields=['explorador', 'anio', 'mes'], name='dpm_exp_periodo_idx'),
        ),
        migrations.AddConstraint(
            model_name='deudapermisomes',
            constraint=models.UniqueConstraint(fields=('permiso', 'anio', 'mes'), name='deuda_permiso_mes_unica'),
        ),
        migrations.AddConstraint(
            model_name='pagodeudapermisomes',
            constraint=models.UniqueConstraint(fields=('pdh', 'deuda'), name='pago_deuda_permiso_mes_unico'),
        ),
    ]
