# Generated by Django 5.2.17 on 2026-09-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0010_deudapermisomes_historicaldeudapermisomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudapermisomes',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('pagada', 'Pagada'), ('consumida_por_sancion', 'Consumida por sanción'), ('condonada', 'Condonada al levantar la sanción'), ('cancelada', 'Cancelada')], default='activa', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicaldeudapermisomes',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('pagada', 'Pagada'), ('consumida_por_sancion', 'Consumida por sanción'), ('condonada', 'Condonada al levantar la sanción'), ('cancelada', 'Cancelada')], default='activa', max_length=25),
        ),
    ]
