# Generated by Django 5.2.17 on 2026-09-05 17:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0011_historicalpermisosesion_permisosesion'),
        ('permisos', '0011_alter_deudapermisomes_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hecho', models.DateField(help_text='Día en que trabajó de más y se generó el crédito.')),
                ('minutos_otorgados', models.PositiveIntegerField(help_text='Minutos que se le reconocen.')),
                ('minutos_consumidos', models.PositiveIntegerField(default=0, help_text='Lo ya aplicado a pagos. Permite el consumo parcial.')),
                ('motivo', models.TextField(help_text='Por qué se le deben estas horas.')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('consumido', 'Consumido'), ('anulado', 'Anulado')], default='activo', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('explorador', models.ForeignKey(help_text='Explorador a quien se le deben las horas.', on_delete=django.db.models.deletion.CASCADE, related_name='creditos_horas', to='empleados.empleado')),
                ('otorgado_por', models.ForeignKey(help_text='Supervisor/admin que reconoce las horas.', on_delete=django.db.models.deletion.CASCADE, related_name='creditos_otorgados', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Crédito de horas',
                'verbose_name_plural': 'Créditos de horas',
                'ordering': ['fecha_hecho', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoCreditoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos', models.PositiveIntegerField(help_text='Minutos de ese crédito que aplica este pago.')),
                ('pdh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_credito', to='permisos.pdh')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='permisos.creditohoras')),
            ],
            options={
                'verbose_name': 'Detalle de consumo de crédito',
                'verbose_name_plural': 'Detalles de consumo de crédito',
            },
        ),
        migrations.AddField(
            model_name='pdh',
            name='creditos_consumidos',
            field=models.ManyToManyField(blank=True, help_text='Horas a favor que cubren este pago.', related_name='pdhs_consumo', through='permisos.ConsumoCreditoHoras', to='permisos.creditohoras'),
        ),
        migrations.CreateModel(
            name='HistoricalCreditoHoras',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_hecho', models.DateField(help_text='Día en que trabajó de más y se generó el crédito.')),
                ('minutos_otorgados', models.PositiveIntegerField(help_text='Minutos que se le reconocen.')),
                ('minutos_consumidos', models.PositiveIntegerField(default=0, help_text='Lo ya aplicado a pagos. Permite el consumo parcial.')),
                ('motivo', models.TextField(help_text='Por qué se le deben estas horas.')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('consumido', 'Consumido'), ('anulado', 'Anulado')], default='activo', max_length=15)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('explorador', models.ForeignKey(blank=True, db_constraint=False, help_text='Explorador a quien se le deben las horas.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('otorgado_por', models.ForeignKey(blank=True, db_constraint=False, help_text='Supervisor/admin que reconoce las horas.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'historical Crédito de horas',
                'verbose_name_plural': 'historical Créditos de horas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='creditohoras',
            index=models.Index(fields=['explorador', 'estado'], name='credito_exp_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='consumocreditohoras',
            constraint=models.UniqueConstraint(fields=('pdh', 'credito'), name='consumo_credito_horas_unico'),
        ),
    ]
