# Generated by Django 5.2.17 on 2026-09-05 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0012_creditohoras_consumocreditohoras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditohoras',
            name='minutos_otorgados',
            field=models.PositiveIntegerField(help_text='Minutos que se le reconocen.', validators=[django.core.validators.MinValueValidator(1, 'Las horas a favor deben ser mayores a cero.'), django.core.validators.MaxValueValidator(1440, 'Las horas a favor no pueden ser mayores a 24.')]),
        ),
        migrations.AlterField(
            model_name='historicalcreditohoras',
            name='minutos_otorgados',
            field=models.PositiveIntegerField(help_text='Minutos que se le reconocen.', validators=[django.core.validators.MinValueValidator(1, 'Las horas a favor deben ser mayores a cero.'), django.core.validators.MaxValueValidator(1440, 'Las horas a favor no pueden ser mayores a 24.')]),
        ),
    ]
