# Generated by Django 5.1.7 on 2025-11-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('solicitudes', '0001_initial'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudcambio',
            options={'ordering': ['-fecha_solicitud']},
        ),
        migrations.AddIndex(
            model_name='solicitudcambio',
            index=models.Index(fields=['explorador_receptor', 'fecha_cambio_turno', 'estado'], name='sol_receptor_fecha_estado_idx'),
        ),
    ]
