# Generated by Django 5.1.7 on 2025-08-23 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('solicitudes', '0001_initial'),
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsolicitudcambio',
            name='turno_destino',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='turnos.turno'),
        ),
        migrations.AddField(
            model_name='historicalsolicitudcambio',
            name='turno_origen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='turnos.turno'),
        ),
        migrations.AddField(
            model_name='historicaltiposolicitudcambio',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='explorador_receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='explorador_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='solicitud_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias', to='solicitudes.solicitudcambio'),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='turno_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_destino', to='turnos.turno'),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='turno_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='turnos.turno'),
        ),
        migrations.AddField(
            model_name='permisodetalle',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permiso', to='solicitudes.solicitudcambio'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitudcambio'),
        ),
        migrations.AddField(
            model_name='historicalsolicitudcambio',
            name='solicitud_origen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.solicitudcambio'),
        ),
        migrations.AddField(
            model_name='historicalpermisodetalle',
            name='solicitud',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.solicitudcambio'),
        ),
        migrations.AddField(
            model_name='historicaldobladadetalle',
            name='solicitud',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.solicitudcambio'),
        ),
        migrations.AddField(
            model_name='historicalcambiopermanentedetalle',
            name='solicitud',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.solicitudcambio'),
        ),
        migrations.AddField(
            model_name='dobladadetalle',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doblada', to='solicitudes.solicitudcambio'),
        ),
        migrations.AddField(
            model_name='cambiopermanentedetalle',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cambio_permanente', to='solicitudes.solicitudcambio'),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='tipo_cambio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.tiposolicitudcambio'),
        ),
        migrations.AddField(
            model_name='historicalsolicitudcambio',
            name='tipo_cambio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.tiposolicitudcambio'),
        ),
    ]
