# Generated by Django 5.2.2 on 2025-08-05 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_supervisor_historicalempleado_supervisor'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitud_cambio', 'Solicitud de Cambio'), ('solicitud_doblada', 'Solicitud de Doblada'), ('solicitud_permiso', 'Solicitud de Permiso'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='empleados.empleado')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitudcambio')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
