# Generated by Django 5.2.2 on 2025-06-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpermisodetalle',
            name='horas_solicitadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='permisodetalle',
            name='horas_solicitadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
