# Generated by Django 5.1.7 on 2025-11-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_solicitudcambio_options_and_more'),
        ('solicitudes', '0002_initial'),
    ]

    operations = [
    ]
