# Generated by Django 5.2.2 on 2025-08-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsolicitudcambio',
            name='fecha_cambio_turno',
            field=models.DateField(blank=True, help_text='Fecha para la cual se solicita el cambio de turno', null=True),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='fecha_cambio_turno',
            field=models.DateField(blank=True, help_text='Fecha para la cual se solicita el cambio de turno', null=True),
        ),
    ]
