# Generated by Django 5.2.2 on 2025-08-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_historicalsolicitudcambio_fecha_cambio_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsolicitudcambio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('pagada', 'Pagada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudcambio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('pagada', 'Pagada')], default='pendiente', max_length=20),
        ),
    ]
