# Generated by Django 5.1.7 on 2025-11-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_asignacionsalaperiodo_and_more'),
        ('solicitudes', '0003_merge_20251111_1435'),
        ('turnos', '0003_merge_20251111_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpermisodetalle',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpermisodetalle',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='permisodetalle',
            name='solicitud',
        ),
        migrations.AddIndex(
            model_name='solicitudcambio',
            index=models.Index(fields=['turno_origen', 'estado'], name='sol_turno_origen_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudcambio',
            index=models.Index(fields=['turno_destino', 'estado'], name='sol_turno_destino_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudcambio',
            index=models.Index(fields=['-fecha_resolucion', 'estado'], name='sol_fecha_resol_estado_idx'),
        ),
        migrations.DeleteModel(
            name='HistoricalPermisoDetalle',
        ),
        migrations.DeleteModel(
            name='PermisoDetalle',
        ),
    ]
