# Generated by Django 5.1.7 on 2025-11-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_add_indexes_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltiposolicitudcambio',
            name='codigo_estrategia',
            field=models.CharField(blank=True, help_text='Código para mapear a la estrategia. Si está vacío, se usa el nombre normalizado. Ejemplos: "CT", "DOBLADA", "CT PERMANENTE"', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tiposolicitudcambio',
            name='codigo_estrategia',
            field=models.CharField(blank=True, help_text='Código para mapear a la estrategia. Si está vacío, se usa el nombre normalizado. Ejemplos: "CT", "DOBLADA", "CT PERMANENTE"', max_length=50, null=True),
        ),
    ]
