# Generated by Django 5.1.7 on 2025-11-21 20:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_historicaltiposolicitudcambio_codigo_estrategia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCambioPermanenteDia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_especifica', models.DateField(blank=True, help_text='Fecha específica seleccionada (ej: 23 de noviembre)', null=True)),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana (0=Lunes, 6=Domingo)', null=True)),
                ('tipo', models.CharField(choices=[('fecha_especifica', 'Fecha Específica'), ('dia_semana', 'Día de Semana')], help_text='Tipo de selección: fecha específica o día de semana', max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cambio_permanente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.cambiopermanentedetalle')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Día de Cambio Permanente',
                'verbose_name_plural': 'historical Días de Cambio Permanente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CambioPermanenteDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_especifica', models.DateField(blank=True, help_text='Fecha específica seleccionada (ej: 23 de noviembre)', null=True)),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana (0=Lunes, 6=Domingo)', null=True)),
                ('tipo', models.CharField(choices=[('fecha_especifica', 'Fecha Específica'), ('dia_semana', 'Día de Semana')], help_text='Tipo de selección: fecha específica o día de semana', max_length=20)),
                ('cambio_permanente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='solicitudes.cambiopermanentedetalle')),
            ],
            options={
                'verbose_name': 'Día de Cambio Permanente',
                'verbose_name_plural': 'Días de Cambio Permanente',
                'indexes': [models.Index(fields=['cambio_permanente', 'tipo'], name='camb_perm_dia_camb_tipo_idx'), models.Index(fields=['fecha_especifica'], name='camb_perm_dia_fecha_idx'), models.Index(fields=['dia_semana'], name='camb_perm_dia_dia_sem_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('dia_semana__isnull', True), ('fecha_especifica__isnull', False), ('tipo', 'fecha_especifica')), models.Q(('dia_semana__isnull', False), ('fecha_especifica__isnull', True), ('tipo', 'dia_semana')), _connector='OR'), name='camb_perman_dia_tipo_valido')],
            },
        ),
    ]
