# Generated by Django 5.2.2 on 2025-12-26 17:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_asignacionsalaperiodo_and_more'),
        ('solicitudes', '0007_add_cambio_permanente_dia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dobladadetalle',
            name='jornada_cedida',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Jornada específica que se cede (si es cesión parcial)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dobladadetalle',
            name='tipo_cesion',
            field=models.CharField(choices=[('cesion_completa', 'Cesión Completa'), ('cesion_parcial_am', 'Cesión Parcial AM'), ('cesion_parcial_pm', 'Cesión Parcial PM')], default='cesion_completa', help_text='Tipo de cesión: completa o parcial (AM/PM)', max_length=50),
        ),
        migrations.AddField(
            model_name='historicaldobladadetalle',
            name='jornada_cedida',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Jornada específica que se cede (si es cesión parcial)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicaldobladadetalle',
            name='tipo_cesion',
            field=models.CharField(choices=[('cesion_completa', 'Cesión Completa'), ('cesion_parcial_am', 'Cesión Parcial AM'), ('cesion_parcial_pm', 'Cesión Parcial PM')], default='cesion_completa', help_text='Tipo de cesión: completa o parcial (AM/PM)', max_length=50),
        ),
        migrations.AlterField(
            model_name='dobladadetalle',
            name='fecha_pago',
            field=models.DateField(help_text='Fecha en que el solicitante devolverá la doblada. Obligatorio: No existen dobladas abiertas.'),
        ),
        migrations.AlterField(
            model_name='historicaldobladadetalle',
            name='fecha_pago',
            field=models.DateField(help_text='Fecha en que el solicitante devolverá la doblada. Obligatorio: No existen dobladas abiertas.'),
        ),
        migrations.CreateModel(
            name='HistoricalDeudaCorporativa',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('minutos', models.IntegerField(default=30, help_text='Minutos de deuda corporativa (típicamente 30 por doblada)')),
                ('fecha_generacion', models.DateField(blank=True, editable=False, help_text='Fecha en que se generó la deuda')),
                ('fecha_doblada', models.DateField(help_text='Fecha en que se realizó la doblada que generó esta deuda')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], default='activa', help_text='Estado de la deuda: activa o cancelada', max_length=20)),
                ('comentario', models.TextField(blank=True, help_text='Comentario opcional sobre la deuda', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('explorador', models.ForeignKey(blank=True, db_constraint=False, help_text='Explorador que acumula la deuda corporativa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud_origen', models.ForeignKey(blank=True, db_constraint=False, help_text='Solicitud que generó esta deuda (opcional)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.solicitudcambio')),
            ],
            options={
                'verbose_name': 'historical Deuda Corporativa',
                'verbose_name_plural': 'historical Deudas Corporativas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDeudaExplorador',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_generacion', models.DateField(blank=True, editable=False, help_text='Fecha en que se generó la deuda')),
                ('fecha_pago_pactada', models.DateField(help_text='Fecha acordada para pagar la deuda')),
                ('fecha_pago_real', models.DateField(blank=True, help_text='Fecha en que se pagó realmente la deuda', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', help_text='Estado de la deuda', max_length=20)),
                ('media_jornada', models.BooleanField(default=True, help_text='True si es media jornada, False si es completa')),
                ('jornada_cedida', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Jornada que se cedió (AM o PM)', max_length=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('acreedor', models.ForeignKey(blank=True, db_constraint=False, help_text='Explorador al que se le debe la jornada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado')),
                ('deudor', models.ForeignKey(blank=True, db_constraint=False, help_text='Explorador que debe la jornada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud_origen', models.ForeignKey(blank=True, db_constraint=False, help_text='Solicitud de doblada que generó esta deuda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.solicitudcambio')),
            ],
            options={
                'verbose_name': 'historical Deuda entre Exploradores',
                'verbose_name_plural': 'historical Deudas entre Exploradores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DeudaCorporativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos', models.IntegerField(default=30, help_text='Minutos de deuda corporativa (típicamente 30 por doblada)')),
                ('fecha_generacion', models.DateField(auto_now_add=True, help_text='Fecha en que se generó la deuda')),
                ('fecha_doblada', models.DateField(help_text='Fecha en que se realizó la doblada que generó esta deuda')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], default='activa', help_text='Estado de la deuda: activa o cancelada', max_length=20)),
                ('comentario', models.TextField(blank=True, help_text='Comentario opcional sobre la deuda', null=True)),
                ('explorador', models.ForeignKey(help_text='Explorador que acumula la deuda corporativa', on_delete=django.db.models.deletion.CASCADE, related_name='deudas_corporativas', to='empleados.empleado')),
                ('solicitud_origen', models.ForeignKey(blank=True, help_text='Solicitud que generó esta deuda (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deudas_corporativas_generadas', to='solicitudes.solicitudcambio')),
            ],
            options={
                'verbose_name': 'Deuda Corporativa',
                'verbose_name_plural': 'Deudas Corporativas',
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['explorador', 'estado'], name='deuda_corp_exp_estado_idx'), models.Index(fields=['fecha_generacion', 'estado'], name='deuda_corp_fecha_estado_idx'), models.Index(fields=['fecha_doblada'], name='deuda_corp_fecha_dob_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeudaExplorador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateField(auto_now_add=True, help_text='Fecha en que se generó la deuda')),
                ('fecha_pago_pactada', models.DateField(help_text='Fecha acordada para pagar la deuda')),
                ('fecha_pago_real', models.DateField(blank=True, help_text='Fecha en que se pagó realmente la deuda', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', help_text='Estado de la deuda', max_length=20)),
                ('media_jornada', models.BooleanField(default=True, help_text='True si es media jornada, False si es completa')),
                ('jornada_cedida', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Jornada que se cedió (AM o PM)', max_length=2)),
                ('acreedor', models.ForeignKey(help_text='Explorador al que se le debe la jornada', on_delete=django.db.models.deletion.CASCADE, related_name='deudas_como_acreedor', to='empleados.empleado')),
                ('deudor', models.ForeignKey(help_text='Explorador que debe la jornada', on_delete=django.db.models.deletion.CASCADE, related_name='deudas_como_deudor', to='empleados.empleado')),
                ('solicitud_origen', models.ForeignKey(help_text='Solicitud de doblada que generó esta deuda', on_delete=django.db.models.deletion.CASCADE, related_name='deuda_generada', to='solicitudes.solicitudcambio')),
            ],
            options={
                'verbose_name': 'Deuda entre Exploradores',
                'verbose_name_plural': 'Deudas entre Exploradores',
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['deudor', 'estado'], name='deuda_deudor_estado_idx'), models.Index(fields=['acreedor', 'estado'], name='deuda_acreedor_estado_idx'), models.Index(fields=['fecha_pago_pactada', 'estado'], name='deuda_fecha_pago_estado_idx')],
            },
        ),
    ]
