# Generated by Django 5.2.2 on 2025-12-26 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_asignacionsalaperiodo_and_more'),
        ('solicitudes', '0008_dobladadetalle_jornada_cedida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dobladadetalle',
            name='empleado_receptor',
            field=models.ForeignKey(blank=True, help_text='Explorador que cubre la doblada (redundante con SolicitudCambio.explorador_receptor, pero útil para consultas directas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dobladas_recibidas', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='historicaldobladadetalle',
            name='empleado_receptor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Explorador que cubre la doblada (redundante con SolicitudCambio.explorador_receptor, pero útil para consultas directas)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado'),
        ),
    ]
