# Generated by Django 5.2.2 on 2026-02-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_competenciaempleado_options_and_more'),
        ('solicitudes', '0010_dobladadetalle_jornada_pago_sabado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cambiopermanentedetalle',
            options={'ordering': ['-fecha_inicio', 'solicitud'], 'verbose_name': 'Detalle de Cambio Permanente', 'verbose_name_plural': 'Detalles de Cambios Permanentes'},
        ),
        migrations.AlterModelOptions(
            name='dobladadetalle',
            options={'ordering': ['-fecha_pago', 'solicitud'], 'verbose_name': 'Detalle de Doblada', 'verbose_name_plural': 'Detalles de Dobladas'},
        ),
        migrations.AlterModelOptions(
            name='historicalcambiopermanentedetalle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Detalle de Cambio Permanente', 'verbose_name_plural': 'historical Detalles de Cambios Permanentes'},
        ),
        migrations.AlterModelOptions(
            name='historicaldobladadetalle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Detalle de Doblada', 'verbose_name_plural': 'historical Detalles de Dobladas'},
        ),
        migrations.AlterModelOptions(
            name='historicaltiposolicitudcambio',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Tipo de Solicitud de Cambio', 'verbose_name_plural': 'historical Tipos de Solicitudes de Cambio'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='tiposolicitudcambio',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Solicitud de Cambio', 'verbose_name_plural': 'Tipos de Solicitudes de Cambio'},
        ),
        migrations.AddIndex(
            model_name='cambiopermanentedetalle',
            index=models.Index(fields=['solicitud'], name='camb_perm_solicitud_idx'),
        ),
        migrations.AddIndex(
            model_name='cambiopermanentedetalle',
            index=models.Index(fields=['fecha_inicio'], name='camb_perm_fecha_inicio_idx'),
        ),
        migrations.AddIndex(
            model_name='dobladadetalle',
            index=models.Index(fields=['solicitud'], name='doblada_solicitud_idx'),
        ),
        migrations.AddIndex(
            model_name='dobladadetalle',
            index=models.Index(fields=['fecha_pago'], name='doblada_fecha_pago_idx'),
        ),
        migrations.AddIndex(
            model_name='dobladadetalle',
            index=models.Index(fields=['empleado_receptor', 'fecha_pago'], name='doblada_receptor_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['destinatario', 'leida'], name='notif_dest_leida_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo'], name='notif_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['fecha_creacion'], name='notif_fecha_creacion_idx'),
        ),
        migrations.AddIndex(
            model_name='tiposolicitudcambio',
            index=models.Index(fields=['activo'], name='tipo_sol_activo_idx'),
        ),
    ]
