# Generated by Django 5.2.2 on 2026-04-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0014_historicaldobladadetalle_jornada_cubre_en_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldobladadetalle',
            name='jornada_cubre_en_pago',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM'), ('AMBAS', 'Ambas (receptor descansa el día completo)')], help_text='Si el receptor tiene doblada (AM+PM) en fecha de pago: qué parte cubre el deudor, o ambas.', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldobladadetalle',
            name='snapshot_turnos_previos',
            field=models.JSONField(blank=True, help_text='Turnos de solicitante/receptor en fechas de cesión y pago ANTES de aplicar la doblada. Clave "explorador_id:YYYY-MM-DD", valor lista de {jornada_nombre, sala_id, tipo_cambio}. Permite revertir la cancelación en 30 min restaurando CT sencillos u otros turnos previos.', null=True),
        ),
    ]
