# Generated by Django 5.2.2 on 2026-06-16 14:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_competenciaempleado_options_and_more'),
        ('solicitudes', '0015_alter_historicaldobladadetalle_jornada_cubre_en_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDobladaPermanenteDetalle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Inicio del rango de vigencia.')),
                ('fecha_fin', models.DateField(help_text='Fin del rango de vigencia.')),
                ('dias_cesion', models.CharField(default='', help_text='Días de la semana que cede el solicitante (los cubre el receptor). 0=lun..6=dom, coma.', max_length=20)),
                ('dias_devolucion', models.CharField(default='', help_text='Días de la semana en que el solicitante devuelve (se dobla). 0=lun..6=dom, coma.', max_length=20)),
                ('minutos_deuda', models.IntegerField(default=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('empleado_receptor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.solicitudcambio')),
            ],
            options={
                'verbose_name': 'historical Detalle de Doblada Permanente',
                'verbose_name_plural': 'historical Detalles de Doblada Permanente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DobladaPermanenteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Inicio del rango de vigencia.')),
                ('fecha_fin', models.DateField(help_text='Fin del rango de vigencia.')),
                ('dias_cesion', models.CharField(default='', help_text='Días de la semana que cede el solicitante (los cubre el receptor). 0=lun..6=dom, coma.', max_length=20)),
                ('dias_devolucion', models.CharField(default='', help_text='Días de la semana en que el solicitante devuelve (se dobla). 0=lun..6=dom, coma.', max_length=20)),
                ('minutos_deuda', models.IntegerField(default=30)),
                ('empleado_receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dobladas_permanentes_recibidas', to='empleados.empleado')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doblada_permanente', to='solicitudes.solicitudcambio')),
            ],
            options={
                'verbose_name': 'Detalle de Doblada Permanente',
                'verbose_name_plural': 'Detalles de Doblada Permanente',
                'ordering': ['-fecha_inicio', 'solicitud'],
                'indexes': [models.Index(fields=['solicitud'], name='dob_perm_solicitud_idx'), models.Index(fields=['fecha_inicio'], name='dob_perm_fecha_idx')],
            },
        ),
    ]
