# Generated by Django 5.2.2 on 2026-06-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0016_historicaldobladapermanentedetalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dobladadetalle',
            name='jornada_pago_sabado',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM'), ('AMBAS', 'Ambas (cubro el día completo; el receptor descansa)')], help_text='Si la fecha de pago es sábado, jornada que el solicitante cubre ese sábado: AM, PM o AMBAS (día completo; en ese caso el receptor descansa y queda debiendo media jornada).', max_length=5, null=True),
        ),
    ]
