# Generated by Django 5.2.2 on 2026-06-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0017_alter_dobladadetalle_jornada_pago_sabado'),
    ]

    operations = [
        migrations.AddField(
            model_name='dobladadetalle',
            name='fecha_pago_semana',
            field=models.DateField(blank=True, help_text='Solo cuando jornada_pago_sabado=AMBAS: día de semana (lun-vie, mismo mes) en que el receptor le devuelve la jornada al solicitante (el receptor dobla y el solicitante descansa).', null=True),
        ),
        migrations.AddField(
            model_name='historicaldobladadetalle',
            name='fecha_pago_semana',
            field=models.DateField(blank=True, help_text='Solo cuando jornada_pago_sabado=AMBAS: día de semana (lun-vie, mismo mes) en que el receptor le devuelve la jornada al solicitante (el receptor dobla y el solicitante descansa).', null=True),
        ),
    ]
