# Generated by Django 5.2.2 on 2026-06-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0018_dobladadetalle_fecha_pago_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dobladapermanentedetalle',
            name='snapshot_turnos_previos',
            field=models.JSONField(blank=True, help_text='Turnos de solicitante/receptor en las fechas afectadas ANTES de aplicar la doblada permanente. Permite revertir al cancelar dentro de los 30 min.', null=True),
        ),
        migrations.AddField(
            model_name='historicaldobladapermanentedetalle',
            name='snapshot_turnos_previos',
            field=models.JSONField(blank=True, help_text='Turnos de solicitante/receptor en las fechas afectadas ANTES de aplicar la doblada permanente. Permite revertir al cancelar dentro de los 30 min.', null=True),
        ),
    ]
