# Generated by Django 5.2.2 on 2026-06-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0019_dobladapermanentedetalle_snapshot_turnos_previos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudacorporativa',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='Fecha en que se pagó la deuda (cuando estado=pagada)', null=True),
        ),
        migrations.AddField(
            model_name='historicaldeudacorporativa',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='Fecha en que se pagó la deuda (cuando estado=pagada)', null=True),
        ),
        migrations.AlterField(
            model_name='deudacorporativa',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='activa', help_text='Estado de la deuda: activa, pagada o cancelada', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaldeudacorporativa',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='activa', help_text='Estado de la deuda: activa, pagada o cancelada', max_length=20),
        ),
    ]
