# Generated by Django 5.2.2 on 2026-06-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0020_deudacorporativa_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsolicitudcambio',
            name='snapshot_turnos_previos',
            field=models.JSONField(blank=True, help_text='Turnos de solicitante/receptor en la(s) fecha(s) afectadas ANTES de aplicar el cambio (usado por CT sencillo). Clave "explorador_id:YYYY-MM-DD", valor lista de {jornada_nombre, sala_id, tipo_cambio}. Permite revertir al cancelar dentro de los 30 min.', null=True),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='snapshot_turnos_previos',
            field=models.JSONField(blank=True, help_text='Turnos de solicitante/receptor en la(s) fecha(s) afectadas ANTES de aplicar el cambio (usado por CT sencillo). Clave "explorador_id:YYYY-MM-DD", valor lista de {jornada_nombre, sala_id, tipo_cambio}. Permite revertir al cancelar dentro de los 30 min.', null=True),
        ),
    ]
