# Generated by Django 5.2.2 on 2026-06-29 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0021_historicalsolicitudcambio_snapshot_turnos_previos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsolicitudcambio',
            name='reemplazada_por',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Solicitud que reemplazó a esta (cuando el turno fue cedido nuevamente tras los 30 min de gavela).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.solicitudcambio'),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='reemplazada_por',
            field=models.ForeignKey(blank=True, help_text='Solicitud que reemplazó a esta (cuando el turno fue cedido nuevamente tras los 30 min de gavela).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplaza_a', to='solicitudes.solicitudcambio'),
        ),
        migrations.AlterField(
            model_name='historicalsolicitudcambio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('pagada', 'Pagada'), ('reemplazada', 'Reemplazada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudcambio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('pagada', 'Pagada'), ('reemplazada', 'Reemplazada')], default='pendiente', max_length=20),
        ),
    ]
