# Generated by Django 5.2.2 on 2026-07-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0022_reemplazada_por_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='dobladadetalle',
            name='submodalidad_semana',
            field=models.CharField(blank=True, choices=[('intercambio_dia', 'Intercambio de día'), ('jornadas_partidas', 'Jornadas partidas (uno AM ambos días, otro PM)'), ('cobertura_misma_semana', 'Cobertura con pago en la misma semana'), ('cambio_doblada', 'Cambio de doblada de la semana')], help_text='Solo CAMBIO DESCANSO entre semana (temporada): distingue el sub-flujo. Las filas antiguas entre-semana sin valor se tratan como intercambio_dia.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicaldobladadetalle',
            name='submodalidad_semana',
            field=models.CharField(blank=True, choices=[('intercambio_dia', 'Intercambio de día'), ('jornadas_partidas', 'Jornadas partidas (uno AM ambos días, otro PM)'), ('cobertura_misma_semana', 'Cobertura con pago en la misma semana'), ('cambio_doblada', 'Cambio de doblada de la semana')], help_text='Solo CAMBIO DESCANSO entre semana (temporada): distingue el sub-flujo. Las filas antiguas entre-semana sin valor se tratan como intercambio_dia.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('solicitud_cambio', 'Solicitud de Cambio'), ('solicitud_doblada', 'Solicitud de Doblada'), ('solicitud_permiso', 'Solicitud de Permiso'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('sancion', 'Sanción')], max_length=20),
        ),
    ]
