# Generated by Django 5.2.2 on 2026-07-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0023_dobladadetalle_submodalidad_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dobladapermanentedetalle',
            name='fechas_cesion',
            field=models.TextField(blank=True, default='', help_text='Fechas específicas de cesión (YYYY-MM-DD, coma). Prioridad sobre dias_cesion.'),
        ),
        migrations.AddField(
            model_name='dobladapermanentedetalle',
            name='fechas_devolucion',
            field=models.TextField(blank=True, default='', help_text='Fechas específicas de devolución (YYYY-MM-DD, coma). Prioridad sobre dias_devolucion.'),
        ),
        migrations.AddField(
            model_name='historicaldobladapermanentedetalle',
            name='fechas_cesion',
            field=models.TextField(blank=True, default='', help_text='Fechas específicas de cesión (YYYY-MM-DD, coma). Prioridad sobre dias_cesion.'),
        ),
        migrations.AddField(
            model_name='historicaldobladapermanentedetalle',
            name='fechas_devolucion',
            field=models.TextField(blank=True, default='', help_text='Fechas específicas de devolución (YYYY-MM-DD, coma). Prioridad sobre dias_devolucion.'),
        ),
    ]
