# Generated by Django 5.2.2 on 2026-07-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_remove_historicalasignacionsalaperiodo_creado_por_and_more'),
        ('solicitudes', '0024_dobladapermanentedetalle_fechas_cesion_and_more'),
        ('turnos', '0009_historicalasignacionespecialmanual_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='solicitudcambio',
            index=models.Index(fields=['explorador_solicitante', '-fecha_solicitud'], name='sol_solicitante_fecha_idx'),
        ),
    ]
