# Generated by Django 5.2.2 on 2026-07-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0025_solicitudcambio_sol_solicitante_fecha_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='dobladadetalle',
            name='es_intercambio',
            field=models.BooleanField(default=False, help_text='True si es un INTERCAMBIO de dobladas (ambos tienen doblada en días distintos y se intercambian): día de cesión el receptor dobla y el solicitante descansa; día de pago el solicitante dobla y el receptor descansa. NO genera ni altera deudas (es un swap de días).'),
        ),
        migrations.AddField(
            model_name='historicaldobladadetalle',
            name='es_intercambio',
            field=models.BooleanField(default=False, help_text='True si es un INTERCAMBIO de dobladas (ambos tienen doblada en días distintos y se intercambian): día de cesión el receptor dobla y el solicitante descansa; día de pago el solicitante dobla y el receptor descansa. NO genera ni altera deudas (es un swap de días).'),
        ),
    ]
