# Generated by Django 5.2.2 on 2026-07-18 18:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_remove_historicalasignacionsalaperiodo_creado_por_and_more'),
        ('solicitudes', '0026_dobladadetalle_es_intercambio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReprogramacionDiaDoblada',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_original', models.DateField(help_text='Día de doblada que no se cumplió (se anuló).')),
                ('jornada_debida', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Jornada que quedó debiendo (la contraria a su jornada ese día).', max_length=2, null=True)),
                ('fecha_reprogramada', models.DateField(blank=True, help_text='Día nuevo en que dobla para pagar (lo organiza el supervisor).', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de programar'), ('pagada', 'Pagada (día reprogramado cumplido)'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('motivo', models.CharField(blank=True, help_text='Motivo de la inasistencia (enfermedad, incapacidad…).', max_length=200, null=True)),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('doblada_origen', models.ForeignKey(blank=True, db_constraint=False, help_text='Doblada aprobada cuyo día no se cumplió.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitudes.solicitudcambio')),
                ('explorador', models.ForeignKey(blank=True, db_constraint=False, help_text='Explorador que no cumplió su día y debe reprogramarlo (deudor).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, db_constraint=False, help_text='Supervisor que registró la inasistencia.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'historical Reprogramación de día de doblada',
                'verbose_name_plural': 'historical Reprogramaciones de día de doblada',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ReprogramacionDiaDoblada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_original', models.DateField(help_text='Día de doblada que no se cumplió (se anuló).')),
                ('jornada_debida', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Jornada que quedó debiendo (la contraria a su jornada ese día).', max_length=2, null=True)),
                ('fecha_reprogramada', models.DateField(blank=True, help_text='Día nuevo en que dobla para pagar (lo organiza el supervisor).', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de programar'), ('pagada', 'Pagada (día reprogramado cumplido)'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('motivo', models.CharField(blank=True, help_text='Motivo de la inasistencia (enfermedad, incapacidad…).', max_length=200, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('doblada_origen', models.ForeignKey(help_text='Doblada aprobada cuyo día no se cumplió.', on_delete=django.db.models.deletion.CASCADE, related_name='reprogramaciones_dia', to='solicitudes.solicitudcambio')),
                ('explorador', models.ForeignKey(help_text='Explorador que no cumplió su día y debe reprogramarlo (deudor).', on_delete=django.db.models.deletion.CASCADE, related_name='reprogramaciones_doblada', to='empleados.empleado')),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Supervisor que registró la inasistencia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprogramaciones_registradas', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Reprogramación de día de doblada',
                'verbose_name_plural': 'Reprogramaciones de día de doblada',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['explorador', 'estado'], name='reprog_explorador_estado_idx'), models.Index(fields=['doblada_origen'], name='reprog_doblada_idx')],
            },
        ),
    ]
