# Generated by Django 5.2.2 on 2026-07-18 20:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0027_historicalreprogramaciondiadoblada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreSemanaOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_lunes', models.DateField(help_text='Lunes de la semana a la que aplica el ajuste.', unique=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('dia_cierre', models.CharField(choices=[('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo'), ('primer_habil', 'Primer día hábil de la semana siguiente')], default='jueves', max_length=15)),
                ('hora_cierre', models.TimeField(default='14:00')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cierre por semana (override)',
                'verbose_name_plural': 'Cierres por semana (overrides)',
                'ordering': ['-semana_lunes'],
            },
        ),
        migrations.CreateModel(
            name='CierreSolicitudesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False, help_text='Si está apagado, no hay ninguna restricción.')),
                ('dia_cierre', models.CharField(choices=[('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo'), ('primer_habil', 'Primer día hábil de la semana siguiente')], default='jueves', max_length=15)),
                ('hora_cierre', models.TimeField(default='14:00', help_text='Hora del día de cierre a partir de la cual se bloquea.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cierre de solicitudes (config)',
                'verbose_name_plural': 'Cierre de solicitudes (config)',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCierreSemanaOverride',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('semana_lunes', models.DateField(db_index=True, help_text='Lunes de la semana a la que aplica el ajuste.')),
                ('habilitado', models.BooleanField(default=True)),
                ('dia_cierre', models.CharField(choices=[('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo'), ('primer_habil', 'Primer día hábil de la semana siguiente')], default='jueves', max_length=15)),
                ('hora_cierre', models.TimeField(default='14:00')),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cierre por semana (override)',
                'verbose_name_plural': 'historical Cierres por semana (overrides)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCierreSolicitudesConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False, help_text='Si está apagado, no hay ninguna restricción.')),
                ('dia_cierre', models.CharField(choices=[('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo'), ('primer_habil', 'Primer día hábil de la semana siguiente')], default='jueves', max_length=15)),
                ('hora_cierre', models.TimeField(default='14:00', help_text='Hora del día de cierre a partir de la cual se bloquea.')),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cierre de solicitudes (config)',
                'verbose_name_plural': 'historical Cierre de solicitudes (config)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
