# Generated by Django 5.2.2 on 2026-07-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0028_cierresemanaoverride_cierresolicitudesconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltiposolicitudcambio',
            name='nombre',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tiposolicitudcambio',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
