# Generated by Django 5.2.2 on 2026-07-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0029_tipo_solicitud_nombre_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreprogramaciondiadoblada',
            name='jornada_pago_previa',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Jornada única que tenía en el día de pago ANTES de doblar; se restaura al cancelar.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='reprogramaciondiadoblada',
            name='jornada_pago_previa',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Jornada única que tenía en el día de pago ANTES de doblar; se restaura al cancelar.', max_length=2, null=True),
        ),
    ]
