# Generated by Django 5.2.16 on 2026-07-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0030_historicalreprogramaciondiadoblada_jornada_pago_previa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dobladadetalle',
            name='snapshot_turnos_resultantes',
            field=models.JSONField(blank=True, help_text='Turnos que la doblada DEJÓ en esas mismas fechas, mismo formato que snapshot_turnos_previos. Al cancelar se compara contra los turnos actuales: si no coinciden, alguien más tocó esos días y revertir pisaría su cambio.', null=True),
        ),
        migrations.AddField(
            model_name='dobladapermanentedetalle',
            name='snapshot_turnos_resultantes',
            field=models.JSONField(blank=True, help_text='Turnos que la doblada permanente DEJÓ en esas mismas fechas, mismo formato que snapshot_turnos_previos. Al cancelar se compara contra los turnos actuales: si no coinciden, alguien más tocó esos días y revertir pisaría su cambio.', null=True),
        ),
        migrations.AddField(
            model_name='historicaldobladadetalle',
            name='snapshot_turnos_resultantes',
            field=models.JSONField(blank=True, help_text='Turnos que la doblada DEJÓ en esas mismas fechas, mismo formato que snapshot_turnos_previos. Al cancelar se compara contra los turnos actuales: si no coinciden, alguien más tocó esos días y revertir pisaría su cambio.', null=True),
        ),
        migrations.AddField(
            model_name='historicaldobladapermanentedetalle',
            name='snapshot_turnos_resultantes',
            field=models.JSONField(blank=True, help_text='Turnos que la doblada permanente DEJÓ en esas mismas fechas, mismo formato que snapshot_turnos_previos. Al cancelar se compara contra los turnos actuales: si no coinciden, alguien más tocó esos días y revertir pisaría su cambio.', null=True),
        ),
        migrations.AddField(
            model_name='historicalsolicitudcambio',
            name='snapshot_turnos_resultantes',
            field=models.JSONField(blank=True, help_text='Turnos que este cambio DEJÓ en las mismas fechas, mismo formato que snapshot_turnos_previos. Al cancelar se compara contra los turnos actuales: si no coinciden, alguien más tocó esos días y revertir pisaría su cambio.', null=True),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='snapshot_turnos_resultantes',
            field=models.JSONField(blank=True, help_text='Turnos que este cambio DEJÓ en las mismas fechas, mismo formato que snapshot_turnos_previos. Al cancelar se compara contra los turnos actuales: si no coinciden, alguien más tocó esos días y revertir pisaría su cambio.', null=True),
        ),
    ]
