# Generated by Django 5.2.16 on 2026-08-01 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0031_snapshot_turnos_resultantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=500)),
                ('cuerpo_texto', models.TextField()),
                ('cuerpo_html', models.TextField(blank=True, default='')),
                ('remitente', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(blank=True, default='', max_length=254)),
                ('destinatarios', models.JSONField(default=list)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('fallido', 'Fallido (agotó reintentos)')], default='pendiente', max_length=12)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_error', models.TextField(blank=True, default='')),
                ('clave_idempotencia', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('disponible_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Correo en cola (outbox)',
                'verbose_name_plural': 'Correos en cola (outbox)',
                'ordering': ['creado_en'],
                'indexes': [models.Index(fields=['estado', 'disponible_en'], name='outbox_estado_disp_idx')],
            },
        ),
    ]
