# Generated by Django 5.2.16 on 2026-08-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0032_emailoutbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsolicitudcambio',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, help_text='Instante en que se canceló la solicitud (por el explorador dentro de su ventana de 30 min, o por gestión). Null si nunca se canceló.', null=True),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, help_text='Instante en que se canceló la solicitud (por el explorador dentro de su ventana de 30 min, o por gestión). Null si nunca se canceló.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsolicitudcambio',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, help_text='Instante en que la solicitud quedó RESUELTA (aprobada o rechazada). De este campo dependen la ventana de cancelación de 30 min y el orden de la guardia LIFO, así que NO se sobrescribe al cancelar: para eso está fecha_cancelacion.', null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcambio',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, help_text='Instante en que la solicitud quedó RESUELTA (aprobada o rechazada). De este campo dependen la ventana de cancelación de 30 min y el orden de la guardia LIFO, así que NO se sobrescribe al cancelar: para eso está fecha_cancelacion.', null=True),
        ),
    ]
