# Generated by Django 5.2.16 on 2026-08-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_historicalsancionempleado_levantada_en_and_more'),
        ('solicitudes', '0033_solicitudcambio_fecha_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsolicitudcambio',
            name='cancelacion_estado',
            field=models.CharField(blank=True, choices=[('', '—'), ('pendiente', 'Cancelación pendiente'), ('aprobada', 'Cancelación aprobada'), ('rechazada', 'Cancelación rechazada'), ('caducada', 'Cancelación caducada')], default='', help_text='Estado de la petición de cancelación. Vacío si nunca se pidió cancelar.', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalsolicitudcambio',
            name='cancelacion_motivo',
            field=models.TextField(blank=True, help_text='Motivo que dio quien pidió cancelar, y/o la respuesta de la contraparte.', null=True),
        ),
        migrations.AddField(
            model_name='historicalsolicitudcambio',
            name='cancelacion_respondida_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsolicitudcambio',
            name='cancelacion_respondida_por',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Quién aprobó o rechazó la cancelación.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='historicalsolicitudcambio',
            name='cancelacion_solicitada_en',
            field=models.DateTimeField(blank=True, help_text='Instante de la PETICIÓN de cancelación. Desde aquí corre el plazo de respuesta de la contraparte.', null=True),
        ),
        migrations.AddField(
            model_name='historicalsolicitudcambio',
            name='cancelacion_solicitada_por',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Quién pidió cancelar (normalmente el solicitante).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='cancelacion_estado',
            field=models.CharField(blank=True, choices=[('', '—'), ('pendiente', 'Cancelación pendiente'), ('aprobada', 'Cancelación aprobada'), ('rechazada', 'Cancelación rechazada'), ('caducada', 'Cancelación caducada')], default='', help_text='Estado de la petición de cancelación. Vacío si nunca se pidió cancelar.', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='cancelacion_motivo',
            field=models.TextField(blank=True, help_text='Motivo que dio quien pidió cancelar, y/o la respuesta de la contraparte.', null=True),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='cancelacion_respondida_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='cancelacion_respondida_por',
            field=models.ForeignKey(blank=True, help_text='Quién aprobó o rechazó la cancelación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelaciones_respondidas', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='cancelacion_solicitada_en',
            field=models.DateTimeField(blank=True, help_text='Instante de la PETICIÓN de cancelación. Desde aquí corre el plazo de respuesta de la contraparte.', null=True),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='cancelacion_solicitada_por',
            field=models.ForeignKey(blank=True, help_text='Quién pidió cancelar (normalmente el solicitante).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelaciones_pedidas', to='empleados.empleado'),
        ),
    ]
