# Generated by Django 5.2.17 on 2026-08-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0034_historicalsolicitudcambio_cancelacion_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionSancionesDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Día al que corresponde la revisión. Único: garantiza una sola ejecución.', unique=True)),
                ('ejecutado_en', models.DateTimeField(auto_now_add=True)),
                ('sanciones_creadas', models.IntegerField(default=0)),
                ('sanciones_levantadas', models.IntegerField(default=0)),
                ('detalle', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Revisión de sanciones por deuda',
                'verbose_name_plural': 'Revisiones de sanciones por deuda',
                'ordering': ['-fecha'],
            },
        ),
    ]
