# Generated by Django 5.2.17 on 2026-08-25 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_historicalsancionempleado_periodo_anio_and_more'),
        ('solicitudes', '0035_revisionsancionesdeuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudacorporativa',
            name='fecha_consumo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deudacorporativa',
            name='sancion_consumidora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deudas_corporativas_consumidas', to='empleados.sancionempleado'),
        ),
        migrations.AddField(
            model_name='historicaldeudacorporativa',
            name='fecha_consumo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldeudacorporativa',
            name='sancion_consumidora',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.sancionempleado'),
        ),
        migrations.AlterField(
            model_name='deudacorporativa',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('pagada', 'Pagada'), ('consumida_por_sancion', 'Consumida por sanción'), ('cancelada', 'Cancelada')], default='activa', help_text='Estado de la deuda: activa, pagada, consumida por sanción o cancelada', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicaldeudacorporativa',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('pagada', 'Pagada'), ('consumida_por_sancion', 'Consumida por sanción'), ('cancelada', 'Cancelada')], default='activa', help_text='Estado de la deuda: activa, pagada, consumida por sanción o cancelada', max_length=25),
        ),
        migrations.AddIndex(
            model_name='deudacorporativa',
            index=models.Index(fields=['explorador', 'estado', 'fecha_doblada'], name='deuda_corp_exp_est_fec_idx'),
        ),
    ]
