# Generated by Django 5.2.17 on 2026-08-25 17:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_historicalsancionempleado_nivel_reincidencia_and_more'),
        ('solicitudes', '0036_deudacorporativa_fecha_consumo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSanciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_ventana_reincidencia', models.PositiveSmallIntegerField(default=30, help_text='Días desde que TERMINA una sanción durante los cuales una nueva cuenta como reincidencia. Si pasan sin sanciones nuevas, el contador vuelve a cero.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Quién hizo el último cambio. Es una decisión de política: debe poder rastrearse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_sancion', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Sanciones (configuración)',
                'verbose_name_plural': 'Sanciones (configuración)',
            },
        ),
        migrations.CreateModel(
            name='HistoricalConfiguracionSanciones',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dias_ventana_reincidencia', models.PositiveSmallIntegerField(default=30, help_text='Días desde que TERMINA una sanción durante los cuales una nueva cuenta como reincidencia. Si pasan sin sanciones nuevas, el contador vuelve a cero.')),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('actualizado_por', models.ForeignKey(blank=True, db_constraint=False, help_text='Quién hizo el último cambio. Es una decisión de política: debe poder rastrearse.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Sanciones (configuración)',
                'verbose_name_plural': 'historical Sanciones (configuración)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
