# Generated by Django 5.2.17 on 2026-08-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0037_configuracionsanciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsanciones',
            name='dias_ventana_reincidencia',
            field=models.PositiveSmallIntegerField(default=45, help_text='Días desde que TERMINA una sanción durante los cuales una nueva cuenta como reincidencia. Si pasan sin sanciones nuevas, el contador vuelve a cero.'),
        ),
        migrations.AlterField(
            model_name='historicalconfiguracionsanciones',
            name='dias_ventana_reincidencia',
            field=models.PositiveSmallIntegerField(default=45, help_text='Días desde que TERMINA una sanción durante los cuales una nueva cuenta como reincidencia. Si pasan sin sanciones nuevas, el contador vuelve a cero.'),
        ),
    ]
