# Generated by Django 5.2.17 on 2026-09-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0038_alter_configuracionsanciones_dias_ventana_reincidencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudacorporativa',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('pagada', 'Pagada'), ('consumida_por_sancion', 'Consumida por sanción'), ('condonada', 'Condonada al levantar la sanción'), ('cancelada', 'Cancelada')], default='activa', help_text='Estado de la deuda: activa, pagada, consumida por sanción o cancelada', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicaldeudacorporativa',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('pagada', 'Pagada'), ('consumida_por_sancion', 'Consumida por sanción'), ('condonada', 'Condonada al levantar la sanción'), ('cancelada', 'Cancelada')], default='activa', help_text='Estado de la deuda: activa, pagada, consumida por sanción o cancelada', max_length=25),
        ),
    ]
