# Generated by Django 5.2.17 on 2026-09-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0039_alter_deudacorporativa_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('solicitud_cambio', 'Solicitud de Cambio'), ('solicitud_doblada', 'Solicitud de Doblada'), ('solicitud_permiso', 'Solicitud de Permiso'), ('aprobacion', 'Aprobación'), ('rechazo', 'Rechazo'), ('sancion', 'Sanción'), ('sancion_levantada', 'Sanción levantada')], max_length=20),
        ),
    ]
